name: Books Library CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
      
      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test
        env:
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}